# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171031_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodSlug',
            field=models.SlugField(unique=True),
        ),
    ]
