# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20171031_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catName',
            field=models.CharField(max_length=128),
        ),
    ]
