# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20171107_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodSlug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
