# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20171107_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='./'),
        ),
    ]
